### ISSUE TITLE
508 response codes use 'active slot' instead of 'slotId'

### ISSUE THREAD

**Issue by sphlabs** [nrkno/sofie-hyperdeck-connection#12]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
If a slot change is initiated by the `slot select` command, the 508 response message that is returned uses the id `active slot` rather than `slotId` to identify the slot. Currently only `slotId` is being matched and passed up the chain.

The transport async handler needs to recognise `active slot` and pass it up as `slotId`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mint-dewit** [comment]
Do you know if this is an issue in all firmware versions or did it change in one of the newer versions?

**Comment by sphlabs** [comment]
Do you mean the Hyperdeck firmware API? I’m not sure, but possibly. I discovered this while trying to work out why companion slot change commands were not updating the variable (which used to work).

This is a different response to the one generated when pulling a drive. It also isn’t mentioned anywhere in the API docs…

>

**Comment by mint-dewit** [comment]
I actually stumbled upon a device with API v1.3 earlier today and it had the same response so I don't think this is recent, when you pull a drive does it send a `slot id` instead or is that not even a `transport info`? (I only have remote access so can't pull drives myself)

I think I'll put in a fix for this while doing the v1.11 work

**Comment by sphlabs** [comment]
From my logs, it looks like a 508 `transport info` returns `active slot` but a 208 code returns `slot id`.

According to the docs a 508 (async) should return the same parameters as a 208 (requested). That does not seem to be the case…

**Comment by mint-dewit** [comment]
Yes, that's also what I'm seeing and the 208 is probably what the initial implementation was based on, I just wondered if it was _ever_ possible to get a 508 in combination with a `slot id` or if it is only `active slot`. Because in the first case I need to handle both cases but in the latter case I can just change the parameter name in the deserialization

**Comment by sphlabs** [comment]
That’s the bit I’m not sure about — if there are situations where a 508 will return `slot id` — given that the docs don’t mention `active slot` at all…
