### ISSUE TITLE
Feature request: Add configuration async handler

### ISSUE THREAD

**Issue by sphlabs** [nrkno/sofie-hyperdeck-connection#13]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Add `configuration` async handler

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Add an async handler for configuration updates that are sent when `notify: configuration` is enabled.

511 configuration:↵
audio input: {“embedded”, “XLR”, “RCA”}↵
video input: {“SDI”, “HDMI”, “component”, …}↵
file format: {File format}↵
↵

**Comment by mint-dewit** [comment]
Version `0.4.4-nightly-feat-v1-11-support-20210414-181626-5180796.0` should contain this

**Comment by sphlabs** [comment]
This still doesn't work in my testing:

`unknown async response: { code: 511, name: 'configuration', params: { 'video input': 'SDI' } }`

Doesn't look like there is support yet for 511 codes in the source?

**Comment by mint-dewit** [comment]
Sorry, I missed an export, should work in `0.4.4-nightly-feat-v1-11-support-20210517-143106-6d15db3.0`

**Comment by sphlabs** [comment]
configuration notifications are working in my testing so far.

However, `ConfigurationGetCommand()` is returning as an error -- I think because code `211` is not listed as a valid synchronous code?

**Comment by sphlabs** [comment]
I am still seeing errors returned when I perform a synchronous ConfigurationGetCommand.

`Connection error - 211 configuration`

**Comment by mint-dewit** [comment]
Could you try again with `0.5.0-nightly-latest-20220108-075415-9ca29b9.0`? I don't have my hyperdeck set up to test currently, sorry in advance.

**Comment by sphlabs** [comment]
Yep, that's fixed it.
