### ISSUE TITLE
Feature request: add clip count command

### ISSUE THREAD

**Issue by sphlabs** [nrkno/sofie-hyperdeck-connection#14]
* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
A `clips get` command, when there are no clips on the timeline, will return a failure code (`107: timeline empty`). In order to guard against this, implement the `clips count` command so one can test for the presence of clips before issuing `clips get`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mint-dewit** [comment]
Added in prerelease `0.4.4-nightly-feat-v1-11-support-20210517-143106-6d15db3.0`

**Comment by sphlabs** [comment]
That works in my testing
