### ISSUE TITLE
Bug / Feature Request : Goto command

### ISSUE THREAD

**Issue by SNRSE** [nrkno/sofie-hyperdeck-connection#7]
* **I'm submitting a ...**
[x] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hey i currently use the libary : Hyperdeck server connection.
I am missing the Command Goto(n) which is used to select which clip should be played.
i tried to add it myself but failed. Please help me

**Comment by mint-dewit** [comment]
Hi, this is the repository for the client connection, if you are having trouble with the server side library please open an issue here: https://github.com/baltedewit/hyperdeck-server-connection/issues

I see the readme on NPM accidentally refers to this repository when cloning, which is incorrect and should be addressed shortly.

If you are in fact having trouble with the client connection: I would guess the n you are referring to would be the same as the clipId property in the goto command?

That can be used as follows:
`new Goto command(undefined, n)`

**Comment by SNRSE** [comment]
oh yeah it's the wrong repo i will aks my question in the other one Thanks
